# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uploadWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormUpload(object):
    def setupUi(self, FormUpload):
        FormUpload.setObjectName("FormUpload")
        FormUpload.resize(969, 635)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        FormUpload.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(FormUpload)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(FormUpload)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(849, 29, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.paperAuthorEdit = QtWidgets.QLineEdit(FormUpload)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.paperAuthorEdit.setFont(font)
        self.paperAuthorEdit.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"")
        self.paperAuthorEdit.setObjectName("paperAuthorEdit")
        self.gridLayout.addWidget(self.paperAuthorEdit, 1, 1, 1, 1)
        self.paperTitleEdit = QtWidgets.QLineEdit(FormUpload)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.paperTitleEdit.setFont(font)
        self.paperTitleEdit.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"")
        self.paperTitleEdit.setObjectName("paperTitleEdit")
        self.gridLayout.addWidget(self.paperTitleEdit, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(FormUpload)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(FormUpload)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(FormUpload)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.paperDateEdit = QtWidgets.QLineEdit(FormUpload)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.paperDateEdit.setFont(font)
        self.paperDateEdit.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"")
        self.paperDateEdit.setObjectName("paperDateEdit")
        self.gridLayout.addWidget(self.paperDateEdit, 2, 1, 1, 1)
        self.paperUploadBtn = QtWidgets.QPushButton(FormUpload)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.paperUploadBtn.setFont(font)
        self.paperUploadBtn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-color: rgb(85, 255, 127);")
        self.paperUploadBtn.setObjectName("paperUploadBtn")
        self.gridLayout.addWidget(self.paperUploadBtn, 4, 0, 1, 1)
        self.paperURLEdit = QtWidgets.QLineEdit(FormUpload)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.paperURLEdit.setFont(font)
        self.paperURLEdit.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"")
        self.paperURLEdit.setObjectName("paperURLEdit")
        self.gridLayout.addWidget(self.paperURLEdit, 3, 1, 1, 1)

        self.retranslateUi(FormUpload)
        QtCore.QMetaObject.connectSlotsByName(FormUpload)

    def retranslateUi(self, FormUpload):
        _translate = QtCore.QCoreApplication.translate
        FormUpload.setWindowTitle(_translate("FormUpload", "Upload"))
        self.label_8.setText(_translate("FormUpload", "作者"))
        self.label_7.setText(_translate("FormUpload", "标题"))
        self.label_10.setText(_translate("FormUpload", "发表日期"))
        self.label_13.setText(_translate("FormUpload", "URL"))
        self.paperUploadBtn.setText(_translate("FormUpload", "确定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormUpload = QtWidgets.QWidget()
    ui = Ui_FormUpload()
    ui.setupUi(FormUpload)
    FormUpload.show()
    sys.exit(app.exec_())
